name: Pages
on:
 push:
   branches:
    - v2
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/setup-python@v2
   - uses: actions/checkout@master
     with:
       fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
   - name: restore or create a python virtualenv
     uses: syphar/restore-virtualenv@v1.2
   - name: Build
     run: |
         make html dir=docs
   - name: Push
     run: echo "push"
